package Model;
// Generated 26 Jul, 2026 1:41:47 PM by Hibernate Tools 4.3.1



/**
 * Contact generated by hbm2java
 */
public class Contact  implements java.io.Serializable {


     private Integer id;
     private String photo;
     private String firstName;
     private String lastName;
     private String phone;
     private String phoneType;
     private String email;
     private String company;
     private String date;
     private String dateType;
     private String grouping;

    public Contact() {
    }

    public Contact(String photo, String firstName, String lastName, String phone, String phoneType, String email, String company, String date, String dateType, String grouping) {
       this.photo = photo;
       this.firstName = firstName;
       this.lastName = lastName;
       this.phone = phone;
       this.phoneType = phoneType;
       this.email = email;
       this.company = company;
       this.date = date;
       this.dateType = dateType;
       this.grouping = grouping;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getPhoneType() {
        return this.phoneType;
    }
    
    public void setPhoneType(String phoneType) {
        this.phoneType = phoneType;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getDateType() {
        return this.dateType;
    }
    
    public void setDateType(String dateType) {
        this.dateType = dateType;
    }
    public String getGrouping() {
        return this.grouping;
    }
    
    public void setGrouping(String grouping) {
        this.grouping = grouping;
    }
}


